### ISSUE TITLE
The same reference is used "using Catalog.Application;"

### ISSUE THREAD

**Issue by JaneConan** [marinasundstrom/item-catalog#12]
WebApi csproj  

Program.cs

https://github.com/marinasundstrom/item-catalog/blob/05cb8578e152ea01e4b5510fcae6e30eadd824f8/Server/AppService/WebApi/Program.cs#L7

and

https://github.com/marinasundstrom/item-catalog/blob/05cb8578e152ea01e4b5510fcae6e30eadd824f8/Server/AppService/WebApi/Program.cs#L8

**Comment by marinasundstrom** [comment]
Thank you, @JaneConan. I have noticed that there are duplicates in a couple of places. I will fix them as I see them.

**Comment by JaneConan** [comment]
Okay, wonderful project, we'll keep an eye on it~ 🌹
